<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>view_gist_detail</name>
   <tag></tag>
   <elementGuidId>b314bb27-2d01-4c8d-9818-0e1e5d3ff470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link-overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='gist-pjax-container']/div/div/div[2]/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-overlay</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://gist.github.com/mapudnopal14/604772f312b6884c18c7765755640779</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      View gist:604772f312b6884c18c7765755640779
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gist-pjax-container&quot;)/div[@class=&quot;container-xl px-3 px-md-4 px-lg-5 mt-4&quot;]/div[@class=&quot;gutter d-flex flex-md-row flex-column&quot;]/div[@class=&quot;col-9 col-md-9 col-12&quot;]/div[@class=&quot;gist-snippet&quot;]/div[@class=&quot;js-gist-file-update-container js-task-list-container file-box&quot;]/a[@class=&quot;link-overlay&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='gist-pjax-container']/div/div/div[2]/div[2]/div[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='this is my third GIST edit'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://gist.github.com/mapudnopal14/604772f312b6884c18c7765755640779')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
